services:
  flashcard-app:
    image: sibacode/flashcard
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/flashcard
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
      GOOGLE_API_KEY: YOUR-API-KEY
    depends_on:
      - db
    networks:
      - flashcard_network

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: flashcard
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - flashcard_network

volumes:
  db_data:

networks:
  flashcard_network:
    driver: bridge
